package com.prodest.view;


public class MainFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameMenu
     */
    public MainFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ConcursoPorCPF = new javax.swing.JMenuItem();
        CandidatoPorCodigo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
//        CadastrarCandidato = new javax.swing.JMenuItem();
//        CadastrarConcurso = new javax.swing.JMenuItem();
        CadastrarProfissao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Consultar");

        ConcursoPorCPF.setText("Concurso pelo CPF do Candidato");
        ConcursoPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcursoPorCPFActionPerformed(evt);
            }
        });
        jMenu1.add(ConcursoPorCPF);

        CandidatoPorCodigo.setText("Candidato pelo Codigo do Concurso");
        CandidatoPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoPorCodigoActionPerformed(evt);
            }
        });
        jMenu1.add(CandidatoPorCodigo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

//        CadastrarCandidato.setText("Candidato");
//        CadastrarCandidato.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                CadastrarCandidatoActionPerformed(evt);
//            }
//        });
//        jMenu2.add(CadastrarCandidato);
//
//        CadastrarConcurso.setText("Concurso");
//        CadastrarConcurso.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                CadastrarConcursoActionPerformed(evt);
//            }
//        });
//        jMenu2.add(CadastrarConcurso);

        CadastrarProfissao.setText("Profissão");
        CadastrarProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProfissaoActionPerformed(evt);
            }
        });
        jMenu2.add(CadastrarProfissao);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1)
                                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel1)
                                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void CandidatoPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {
        new BuscaPorCodigo().run();
    }

    private void ConcursoPorCPFActionPerformed(java.awt.event.ActionEvent evt) {
        new BuscaPorCpfForm().run();
    }

    private void CadastrarConcursoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CadastrarProfissaoActionPerformed(java.awt.event.ActionEvent evt) { new CadastrarProfissao().run();}



    private void CadastrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrameMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
//    private javax.swing.JMenuItem CadastrarCandidato;
//    private javax.swing.JMenuItem CadastrarConcurso;
    private javax.swing.JMenuItem CadastrarProfissao;
    private javax.swing.JMenuItem CandidatoPorCodigo;
    private javax.swing.JMenuItem ConcursoPorCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration
}
